### ISSUE TITLE
Variable CNN-1/conv/weights does not exist

### ISSUE THREAD

**Issue by ericalingyuan** [galsang/ABCNN#3]
ValueError: Variable CNN-1/conv/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope? Anyone has the same issue?

Traceback (most recent call last):
  File "train.py", line 129, in <module>
    data_type=params["data_type"], word2vec=params["word2vec"])
  File "train.py", line 26, in train
    num_features=train_data.num_features, num_classes=num_classes, num_layers=num_layers)
  File "/Users/yuanling/Downloads/ABCNN-master/ABCNN.py", line 176, in __init__
    LI_1, LO_1, RI_1, RO_1 = CNN_layer(variable_scope="CNN-1", x1=x1_expanded, x2=x2_expanded, d=d0)
  File "/Users/yuanling/Downloads/ABCNN-master/ABCNN.py", line 152, in CNN_layer
    left_conv = convolution(name_scope="left", x=pad_for_wide_conv(x1), d=d)
  File "/Users/yuanling/Downloads/ABCNN-master/ABCNN.py", line 64, in convolution
    scope=scope
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 918, in convolution
    outputs = layer.apply(inputs)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 320, in apply
    return self.__call__(inputs, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 286, in __call__
    self.build(input_shapes[0])
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 138, in build
    dtype=self.dtype)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 349, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1389, in wrapped_custom_getter
    *args, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 275, in variable_getter
    variable_getter=functools.partial(getter, **kwargs))
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 228, in _add_variable
    trainable=trainable and self.trainable)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1334, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1326, in _model_variable_getter
    custom_getter=getter, use_resource=use_resource)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 262, in model_variable
    use_resource=use_resource)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 217, in variable
    use_resource=use_resource)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/Applications/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 671, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable CNN-1/conv/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by galsang** [comment]
Please report your environment where you did the experiment.
I recommend you following the development environment in the README.md such as the version of Python (Python 3) or libraries.

**Comment by haibin894609937** [comment]
I get the same error 
ValueError: Variable CNN-1/conv/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by haibin894609937** [comment]
I got the errors,,,,,,,,my tensorflow version is higher then recommended

**Comment by galsang** [comment]
I've met the same error after updating Tensorflow to 1.2.1 and fixed the bug.
Please check the latest version of codes.

Thanks.
